server:
  port: 5002

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true

spring:
  application:
    name: stock-query-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/stockQuery?createDatabaseIfNotExist=true
    username: root
    password: techbankRootPsw
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stockConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

api:
  find-all-stock:
    description: 'REST API to get all stocks'
    notes: 'This API is used to get all stocks for all companies.'
  find-stocks-by-company-code:
    description: 'REST API to get stocks by company code'
    notes: 'This API is used to get all stocks of a company.'
  find-stocks-by-company-code-and-between-creation-date:
    description: 'REST API to get stocks by company code for a date range'
    notes: 'This API is used to get all stocks of a company for a range of creation date.'